package main

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// Sentinel errors so main can map a failure to the right exit code without
// matching on message text.
var (
	// ErrNoDefinition means the directory holds no pipeline definition.
	ErrNoDefinition = errors.New("no pipeline definition")
	// ErrCompile means the definition exists but does not compile, a bug in
	// the definition file, distinct from a step failing at run time.
	ErrCompile = errors.New("pipeline definition did not compile")
	// ErrToolchain means the Go toolchain is unavailable.
	ErrToolchain = errors.New("go toolchain not found on PATH")
	// ErrNoTargets means the definition compiles but exposes no exported
	// function the runner can call.
	ErrNoTargets = errors.New("definition exposes no runnable targets")
	// ErrDuplicateTarget means two exported functions map to the same command,
	// which would make one silently unreachable.
	ErrDuplicateTarget = errors.New("two functions map to the same command")
	// ErrAlreadyInitialised means a definition directory already exists.
	// Scaffolding refuses rather than overwriting, because a definition holds
	// real deploy logic and clobbering it would be unrecoverable.
	ErrAlreadyInitialised = errors.New("a definition already exists here")
	// ErrNamespaceClash means a namespace directory and a root target claim the
	// same word. Rejected rather than resolved by precedence: precedence makes
	// one of the two silently unreachable.
	ErrNamespaceClash = errors.New("a namespace and a target claim the same command")
	// ErrTooDeep means a directory sits below the one namespace level targets
	// may occupy.
	ErrTooDeep = errors.New("targets are nested too deep")
	// ErrGenerate means the dispatcher could not be produced or written. It is
	// always a fault in lath itself, never in the author's definition, which
	// is why it maps to the internal-error exit code.
	ErrGenerate = errors.New("could not generate the dispatcher")
)

// definition describes a project's pipeline source as found on disk.
type definition struct {
	// Dir is the definition directory, relative to the working directory.
	Dir string
	// Files are the hashed inputs, sorted, for display and diagnosis.
	Files []string
	// Hash is the short content hash naming this definition's cache entry.
	Hash string
}

// scan finds the definition in dir and hashes its inputs.
//
// Why it hashes every .go file rather than one named entry point: a definition
// may be split across as many files as the author likes, and a rebuild must
// trigger on any of them. Requiring a manifest of which files count would be
// configuration that exists only to be forgotten.
//
// Invariant: the hash is stable across runs and machines for identical content
// the file list is sorted, and each file contributes its name and length as
// well as its bytes, so two different splits of the same total bytes cannot
// collide.
func scan(dir string) (definition, error) {
	files, err := hashableFiles(dir)
	if err != nil {
		return definition{}, err
	}
	if len(files) == 0 {
		return definition{}, fmt.Errorf("scan %s: %w", dir, ErrNoDefinition)
	}
	// Sorted so the hash does not depend on filesystem iteration order, which
	// differs between platforms and would cause spurious cache misses.
	sort.Strings(files)

	h := sha256.New()

	// The build environment is part of the identity, not just the source.
	//
	// Without this, upgrading lath or the Go toolchain leaves every cached
	// binary in place: the definition is unchanged, so the hash is unchanged,
	// so a stale binary, generated by the previous dispatcher template and
	// compiled by the previous compiler, runs silently and forever.
	//
	// The executable's own size and modification time are mixed in as well as
	// its version string, because a development build always reports the same
	// version ("dev") no matter how many times it is rebuilt. Costing one extra
	// compile after reinstalling an identical binary is a trivial price for
	// never running a stale one.
	fmt.Fprintf(h, "lath\x00%s\x00%s\x00", version, goVersionString())
	if exe, err := os.Executable(); err == nil {
		if info, err := os.Stat(exe); err == nil {
			fmt.Fprintf(h, "exe\x00%d\x00%d\x00", info.Size(), info.ModTime().UnixNano())
		}
	}

	for _, rel := range files {
		content, err := os.ReadFile(filepath.Join(dir, rel))
		if err != nil {
			return definition{}, fmt.Errorf("scan %s/%s: %w", dir, rel, err)
		}
		// Path and length are mixed in as a length-prefixed frame so that
		// moving bytes between files changes the hash. Hashing concatenated
		// content alone would not. The path is RELATIVE to the definition
		// root, so the hash does not depend on where the repository sits.
		fmt.Fprintf(h, "%s\x00%d\x00", filepath.ToSlash(rel), len(content))
		h.Write(content)
	}

	// Locally-replaced modules are part of the source too. Without this a
	// definition under development reuses a stale binary after its engine
	// changes, see localReplaceHash.
	replaceDigest, err := localReplaceHash(dir)
	if err != nil {
		return definition{}, err
	}
	if replaceDigest != "" {
		fmt.Fprintf(h, "replaces\x00%s\x00", replaceDigest)
	}

	return definition{
		Dir:   dir,
		Files: files,
		Hash:  hex.EncodeToString(h.Sum(nil))[:hashPrefixLen],
	}, nil
}

// hashableFiles lists the definition's source files, relative to dir.
//
// Covers the definition root AND every namespace directory: a hash that ignored
// namespace files would not change when secrets/push.go was edited, and lath
// would silently run a stale binary. internal/ is included too, helpers are
// compiled into the dispatcher, so a change there changes the result.
func hashableFiles(dir string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			if os.IsNotExist(err) && path == dir {
				return fmt.Errorf("scan %s: %w", dir, ErrNoDefinition)
			}
			return err
		}
		if d.IsDir() {
			// Dot- and underscore-prefixed directories are invisible to the Go
			// tool, so nothing inside them can affect the build.
			if path != dir && (strings.HasPrefix(d.Name(), ".") || strings.HasPrefix(d.Name(), "_")) {
				return fs.SkipDir
			}
			return nil
		}
		name := d.Name()
		// The generated dispatcher is derived FROM these files, so including
		// it would make the hash depend on its own output, every run would
		// miss the cache. Excluded defensively as well as removed after each
		// build, because a crashed run can leave one behind.
		if name == generatedFileName {
			return nil
		}
		if !strings.HasSuffix(name, goFileSuffix) && name != goModFile && name != goSumFile {
			return nil
		}
		rel, relErr := filepath.Rel(dir, path)
		if relErr != nil {
			return relErr
		}
		out = append(out, rel)
		return nil
	})
	if err != nil {
		if errors.Is(err, ErrNoDefinition) {
			return nil, err
		}
		return nil, fmt.Errorf("scan %s: %w", dir, err)
	}
	return out, nil
}

// cacheDir returns the directory holding compiled pipelines.
//
// Falls back to the OS temp directory when a user cache directory is
// unavailable (some CI images set no HOME): a slower rebuild every run is a
// far better failure than refusing to deploy.
func cacheDir() string {
	root, err := os.UserCacheDir()
	if err != nil {
		root = os.TempDir()
	}
	return filepath.Join(root, cacheSubdir)
}

// build compiles the definition to binPath, streaming compiler diagnostics to
// stderr so a type error in the definition reaches the author verbatim.
//
// Invariant: returns an error wrapping ErrCompile for a compilation failure and
// ErrToolchain when go is absent, so the caller can exit with the right code.
func build(d definition, binPath string, stderr, stdout *os.File) error {
	if _, err := exec.LookPath(goToolName); err != nil {
		return fmt.Errorf("build %s: %w", d.Dir, ErrToolchain)
	}
	if err := os.MkdirAll(filepath.Dir(binPath), cacheDirPerm); err != nil {
		return fmt.Errorf("build %s: create cache dir: %w", d.Dir, err)
	}

	cmd := exec.Command(goToolName, "build", "-o", binPath, ".")
	cmd.Dir = d.Dir
	cmd.Env = append(os.Environ(), goWorkOffEnv)
	cmd.Stdout, cmd.Stderr = stdout, stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("build %s: %w", d.Dir, ErrCompile)
	}
	return nil
}

// defaultGoVersion reports the toolchain that compiled this binary.
func defaultGoVersion() string { return runtime.Version() }
