package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

// generatedFileName is where the dispatcher is written, inside the definition
// directory.
//
// It must live there because Go requires every file of a package to share one
// directory. The dispatcher calls the author's functions directly, so it is
// part of their package. The zz_ prefix sorts it last in a listing, and the
// name is fixed so a stale copy from an interrupted run is found and removed
// rather than accumulating.
const generatedFileName = "zz_lath_generated.go"

// generatedHeader marks the file. Checked before deleting, so lath can never
// remove a hand-written file that happens to share the name.
const generatedHeader = "// Code generated by lath. DO NOT EDIT."

// dispatch is one rendered case in the generated switch.
//
// Every field is a finished string computed in Go. The template performs NO
// logic. No conditionals on signature, no string comparison, because a
// mistake in template logic surfaces as a compile error in code the author
// never wrote, pointing at a line number that means nothing to them.
type dispatch struct {
	// Word is the single word this case matches, a root target's command, or
	// a target's name within its namespace.
	Word string
	// Statement is the complete Go call, e.g. `err = secrets.Push(ctx)`.
	Statement string
	// Doc is the help text, already trimmed to one line.
	Doc string
}

// namespaceGroup is one nested switch: a namespace and the targets inside it.
type namespaceGroup struct {
	// Name is the word the user types first, e.g. "secrets".
	Name string
	// Alias is the import alias used to qualify calls. Always derived from the
	// directory name rather than the package's own name, so a directory whose
	// name is not a valid Go identifier still works.
	Alias string
	// ImportPath is the definition module's path to the namespace package.
	ImportPath string
	// Targets are the commands inside the namespace.
	Targets []dispatch
}

// dispatcherData is the template's entire input.
type dispatcherData struct {
	Header string
	// Roots are targets in the definition root.
	Roots []dispatch
	// Groups are the namespaces, each rendered as a nested switch.
	Groups []namespaceGroup
	// NeedsCtx gates the declaration of ctx and the import of context.
	//
	// Go rejects an unused variable and an unused import, so declaring either
	// unconditionally breaks any definition whose targets all omit it, a
	// definition of only `func Name() error` targets, for instance.
	//
	// There is no NeedsArgs equivalent: variadic targets receive os.Args[N:]
	// inline rather than a declared variable, so no unused-variable case can
	// arise for them.
	NeedsCtx bool
	// ExitUsage and ExitFail are threaded through rather than hardcoded in the
	// template so the generated binary's exit codes cannot drift from the
	// runner's own.
	ExitUsage int
	ExitFail  int
	// Debuggable gates every line of step-debugger support.
	//
	// True only when the definition already requires the pipeline module.
	// Emitting the debug code unconditionally would force a definition of
	// plain shell-replacement tasks. One that never builds a Pipeline, to
	// take a dependency on pipeline and its debug package purely to compile
	// generated code it can never use.
	Debuggable bool
	// SocketFlag is the argument carrying a debug session's socket path,
	// threaded through so the generated parser and the runner that writes it
	// cannot drift apart.
	SocketFlag string
	// WaitFlag is the argument carrying the attach timeout.
	WaitFlag string
	// TTYFlag is the argument saying the run owns the terminal.
	TTYFlag string
}

// dispatcherTemplate renders the main function.
//
// Invariant: the identifiers ctx and err are declared here and referenced by
// Signature.Statement. Renaming one without the other produces a dispatcher
// that does not compile.
var dispatcherTemplate = template.Must(template.New("main").Parse(`{{.Header}}
//
// Regenerated on every run from the exported functions in this directory, then
// deleted. Editing it is pointless; edit the functions instead.

package main

import (
{{- if .NeedsCtx}}
	"context"
{{- end}}
	"fmt"
	"os"
{{- if .NeedsCtx}}
	"os/signal"
	"syscall"
{{- end}}
{{- range .Groups}}
	{{.Alias}} "{{.ImportPath}}"
{{- end}}
{{- if .Debuggable}}

	"time"

	"github.com/ubgo/lath/pipeline"
	"github.com/ubgo/lath/pipeline/debug"
{{- end}}
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit({{.ExitUsage}})
	}
{{- if .NeedsCtx}}
	// Cancelled on Ctrl-C, so every target that takes a context gets clean
	// shutdown without installing its own handler. A target receiving a
	// context.Background() here would have to re-implement signal handling to
	// be interruptible at all. Which is boilerplate a task runner should
	// absorb, not distribute.
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
{{- end}}

{{- if .Debuggable}}
	// A debug session, if lath opened one. The socket path arrives in argv
	// rather than the environment so it is visible to ps and cannot be
	// inherited by accident; it is stripped here so the author's target never
	// sees a flag it did not define.
	//
	// Arming is global because NewState is called inside the author's own
	// functions, which this dispatcher runs before and cannot reach into. An
	// opt-in argument in every definition would fail silently the first time
	// someone forgot it, and --debug quietly doing nothing is the worst shape
	// a debugging tool can fail in.
	if sock := takeSocketFlag(); sock != "" {
		ln, lnErr := debug.Listen(sock, nil)
		if lnErr != nil {
			fmt.Fprintln(os.Stderr, "lath:", lnErr)
			os.Exit({{.ExitFail}})
		}
		defer ln.Close()

		if takeValueFlag("{{.TTYFlag}}") == "1" {
			// The panel draws only at pauses, so a running step may use the
			// terminal, see pipeline.YieldTerminal.
			pipeline.YieldTerminal()
		}
		wait := takeWaitFlag()
		// Armed lazily: waiting for an operator happens when the first
		// pipeline is built, not now. A target that rejects its arguments , 
		// an unknown environment, a protected one without the flag, must
		// fail immediately rather than after someone has attached to watch it
		// do nothing.
		//
		// Arming is all that is needed beyond this: pipeline.NewState gives an
		// attached debugger the run's output automatically, alongside whatever
		// reporter the definition already passes. See pipeline.ReporterSource.
		pipeline.AttachDebuggerFunc(func() (pipeline.Debugger, error) {
			fmt.Fprintf(os.Stderr, "lath: waiting for a debugger (%s)\n  attach with:  lath tui\n", wait)
			srv, accErr := ln.Accept({{if .NeedsCtx}}ctx{{else}}context.Background(){{end}}, wait)
			if accErr != nil {
				return nil, accErr
			}
			return srv, nil
		})
	}
{{- end}}

	var err error
	switch lower(os.Args[1]) {
{{- range .Roots}}
	case "{{.Word}}":
		{{.Statement}}
{{- end}}
{{- range .Groups}}
	case "{{.Name}}":
		if len(os.Args) < 3 {
			fmt.Fprintf(os.Stderr, "%s needs a target\n\n", "{{.Name}}")
			usage()
			os.Exit({{$.ExitUsage}})
		}
		switch lower(os.Args[2]) {
	{{- range .Targets}}
		case "{{.Word}}":
			{{.Statement}}
	{{- end}}
		default:
			fmt.Fprintf(os.Stderr, "unknown target %q in %q\n\n", os.Args[2], "{{.Name}}")
			usage()
			os.Exit({{$.ExitUsage}})
		}
{{- end}}
	default:
		fmt.Fprintf(os.Stderr, "unknown command %q\n\n", os.Args[1])
		usage()
		os.Exit({{.ExitUsage}})
	}

{{- if .Debuggable}}
	// A debugger that was armed but never attached is a failed run, not a
	// quiet one: the operator asked to supervise and did not get to.
	if dbgErr := pipeline.DebuggerError(); dbgErr != nil {
		fmt.Fprintln(os.Stderr, "lath:", dbgErr)
		os.Exit({{.ExitFail}})
	}
{{- end}}

	if err != nil {
		fmt.Fprintln(os.Stderr, "FAILED:", err)
		os.Exit({{.ExitFail}})
	}
}

// usage lists the targets this definition exposes.
func usage() {
	fmt.Fprintln(os.Stderr, "targets:")
{{- range .Roots}}
	fmt.Fprintf(os.Stderr, "  %-18s %s\n", {{printf "%q" .Word}}, {{printf "%q" .Doc}})
{{- end}}
{{- range .Groups}}
	fmt.Fprintf(os.Stderr, "\n  %s\n", {{printf "%q" .Name}})
	{{- range .Targets}}
	fmt.Fprintf(os.Stderr, "    %-16s %s\n", {{printf "%q" .Word}}, {{printf "%q" .Doc}})
	{{- end}}
{{- end}}
}

{{- if .Debuggable}}

// takeWaitFlag removes lath's attach-timeout argument and returns it, falling
// back to the default when absent or unparseable, a malformed value must not
// stop a run that is otherwise ready to go.
func takeWaitFlag() time.Duration {
	raw := takeValueFlag("{{.WaitFlag}}")
	if raw == "" {
		return debug.DefaultAttachTimeout
	}
	d, err := time.ParseDuration(raw)
	if err != nil || d <= 0 {
		return debug.DefaultAttachTimeout
	}
	return d
}

// takeSocketFlag removes lath's debug-socket argument from os.Args and returns
// its value, or empty when absent.
func takeSocketFlag() string {
	return takeValueFlag("{{.SocketFlag}}")
}

// takeValueFlag removes "name=value" from os.Args and returns the value.
func takeValueFlag(name string) string {
	prefix := name + "="
	out := os.Args[:0:0]
	value := ""
	for _, a := range os.Args {
		if len(a) > len(prefix) && a[:len(prefix)] == prefix {
			value = a[len(prefix):]
			continue
		}
		out = append(out, a)
	}
	os.Args = out
	return value
}
{{- end}}

// lower folds ASCII case so command matching is case-insensitive. Hand-rolled
// rather than importing strings, to keep the generated file's import set to
// exactly what the dispatcher body needs. An unused import would not compile.
func lower(s string) string {
	b := []byte(s)
	for i := range b {
		if b[i] >= 'A' && b[i] <= 'Z' {
			b[i] += 'a' - 'A'
		}
	}
	return string(b)
}
`))

// generate writes the dispatcher into dir and returns its path.
//
// Invariant: any pre-existing generated file is removed first, so an
// interrupted previous run cannot leave a dispatcher for functions that no
// longer exist. Returns an error wrapping ErrGenerate on any failure.
func generate(dir string, targets []Target) (string, error) {
	path := filepath.Join(dir, generatedFileName)
	if err := removeGenerated(path); err != nil {
		return "", err
	}

	modulePath, err := definitionModulePath(dir)
	if err != nil {
		return "", err
	}

	debuggable, err := usesPipeline(dir)
	if err != nil {
		return "", err
	}
	data := dispatcherData{
		Header:     generatedHeader,
		NeedsCtx:   anySignature(targets, SigCtxError, SigCtxArgsError) || debuggable,
		ExitUsage:  exitUsage,
		ExitFail:   exitPipeline,
		Debuggable: debuggable,
		SocketFlag: socketFlag,
		WaitFlag:   waitFlag,
		TTYFlag:    ttyFlag,
	}

	// Namespaces are rendered in the order they first appear in the sorted
	// target list, so the generated file is byte-stable across runs.
	groupIndex := map[string]int{}
	for _, t := range targets {
		// A root target consumes os.Args[2:]; a namespaced one os.Args[3:].
		// Passed as an expression rather than a declared variable so no
		// unused-variable case can arise in the generated file.
		argsExpr := "os.Args[2:]"
		qualified := t.Func
		if t.Namespace != "" {
			argsExpr = "os.Args[3:]"
			qualified = namespaceAlias(t.Namespace) + "." + t.Func
		}
		stmt, err := t.Sig.Statement(qualified, argsExpr)
		if err != nil {
			// Unreachable for a Signature produced by classify, which only
			// emits declared values. Reported rather than ignored so adding a
			// Signature without a call form fails loudly here instead of
			// generating a case that silently does nothing.
			return "", fmt.Errorf("generate dispatcher for %s: %w: %w", t.Func, ErrGenerate, err)
		}

		word := t.Command
		if t.Namespace != "" {
			word = strings.TrimPrefix(t.Command, t.Namespace+commandSeparator)
		}
		entry := dispatch{Word: word, Statement: stmt, Doc: describe(t)}

		if t.Namespace == "" {
			data.Roots = append(data.Roots, entry)
			continue
		}
		i, seen := groupIndex[t.Namespace]
		if !seen {
			data.Groups = append(data.Groups, namespaceGroup{
				Name:       t.Namespace,
				Alias:      namespaceAlias(t.Namespace),
				ImportPath: modulePath + "/" + t.Namespace,
			})
			i = len(data.Groups) - 1
			groupIndex[t.Namespace] = i
		}
		data.Groups[i].Targets = append(data.Groups[i].Targets, entry)
	}

	var buf bytes.Buffer
	if err := dispatcherTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("generate dispatcher: %w: %w", ErrGenerate, err)
	}
	if err := os.WriteFile(path, buf.Bytes(), generatedFilePerm); err != nil {
		return "", fmt.Errorf("generate dispatcher: %w: %w", ErrGenerate, err)
	}
	return path, nil
}

// namespaceAlias converts a directory name to a Go import alias.
//
// Always aliased, never left to the package's own name: a directory called
// "my-scripts" cannot be `package my-scripts`, and relying on the declared
// package name would mean parsing it out and hoping the two agree. An alias
// derived from the directory is one rule that always holds.
func namespaceAlias(namespace string) string {
	var b strings.Builder
	b.WriteString(namespaceAliasPrefix)
	for _, r := range namespace {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

// definitionModulePath reads the module path from the definition's go.mod, so
// generated imports address its namespace packages correctly.
func definitionModulePath(dir string) (string, error) {
	content, err := os.ReadFile(filepath.Join(dir, goModFile))
	if err != nil {
		return "", fmt.Errorf("generate dispatcher: reading %s: %w: %w", goModFile, ErrGenerate, err)
	}
	if m := modulePathPattern.FindSubmatch(content); m != nil {
		return string(m[1]), nil
	}
	return "", fmt.Errorf("generate dispatcher: no module path in %s: %w", goModFile, ErrGenerate)
}

// pipelineModulePath is the module a definition must require before any
// step-debugger code is generated for it.
const pipelineModulePath = "github.com/ubgo/lath/pipeline"

// usesPipeline reports whether the definition requires the pipeline module.
//
// Read from go.mod rather than by scanning imports, because the question is
// not "does some file import it today" but "can generated code that imports it
// compile", and that is exactly what a require line answers. A definition
// that dropped its last pipeline but kept the require still builds; one that
// imports it without requiring it does not build at all, with or without us.
func usesPipeline(dir string) (bool, error) {
	blob, err := os.ReadFile(filepath.Join(dir, "go.mod"))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("reading %s: %w", filepath.Join(dir, "go.mod"), err)
	}
	return requiresPipeline.Match(blob), nil
}

// requiresPipeline matches a require of the pipeline module, in either the
// single-line or the grouped form, and not a longer path that merely starts
// the same way, pipeline/debug is a package, never a module.
var requiresPipeline = regexp.MustCompile(
	`(?m)^\s*(?:require\s+)?` + regexp.QuoteMeta(pipelineModulePath) + `\s+v`)

// modulePathPattern extracts the path from a `module x/y` line. Matched
// textually rather than via the modfile package to keep this binary free of a
// dependency it would otherwise not need.
var modulePathPattern = regexp.MustCompile(`(?m)^module\s+(\S+)\s*$`)

// removeGenerated deletes the dispatcher, refusing to touch anything that does
// not carry the generated header, so a hand-written file sharing the name is
// never destroyed.
//
// A missing file is success, not an error: the function's contract is "this
// path holds no generated file afterwards", which is already true.
func removeGenerated(path string) error {
	content, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("remove %s: %w", path, err)
	}
	if !bytes.HasPrefix(content, []byte(generatedHeader)) {
		return fmt.Errorf("refusing to overwrite %s: it exists but is not lath-generated: %w",
			path, ErrGenerate)
	}
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("remove %s: %w", path, err)
	}
	return nil
}

// anySignature reports whether any target has one of the given signatures.
// Used to decide which identifiers the dispatcher may legally declare.
func anySignature(targets []Target, want ...Signature) bool {
	for _, t := range targets {
		for _, w := range want {
			if t.Sig == w {
				return true
			}
		}
	}
	return false
}
